using CoddLoom.Condition;
using CoddLoom.Input;
using CoddLoom.MariaDb;
using CoddLoom.MySql;
using CoddLoom.Oracle;
using CoddLoom.Params;
using CoddLoom.PostgreSql;
using CoddLoom.Sql;
using CoddLoom.SqlServer;
using CoddLoom.Table;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Data;
using System.Linq;

namespace CoddLoom.Tests.UnitTest;

[TestClass]
public class ProviderBuilderContractTest
{
    [TestMethod]
    public void ColumnTypes_CoverEverySupportedDbType_ForEveryProvider()
    {
        foreach (var provider in Enum.GetValues<Provider>())
        {
            var builder = CreateBuilder(provider);
            foreach (var dbType in SupportedDbTypes)
            {
                Assert.AreEqual(ExpectedColumnType(provider, dbType), builder.ColumnType(dbType),
                    $"Unexpected mapping for {provider}/{dbType}.");
            }

            Assert.ThrowsExactly<NotSupportedException>(() => builder.ColumnType((DbType)int.MaxValue),
                $"{provider} must reject DbType values it cannot persist safely.");
        }
    }

    [TestMethod]
    public void SpecializedColumns_UseEachProviderNativeSyntax()
    {
        AssertCreateSql(Provider.Sqlite,
            "id INTEGER PRIMARY KEY AUTOINCREMENT",
            "code TEXT NOT NULL", "fixedCode TEXT", "payload BLOB", "amount REAL");
        AssertCreateSql(Provider.MySql,
            "id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL",
            "code VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL",
            "fixedCode CHAR(8) CHARACTER SET latin1", "payload BLOB", "amount DECIMAL(12,3)");
        AssertCreateSql(Provider.MariaDb,
            "id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL",
            "code VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL",
            "fixedCode CHAR(8) CHARACTER SET latin1", "payload BLOB", "amount DECIMAL(12,3)");
        AssertCreateSql(Provider.SqlServer,
            "id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL",
            "code NVARCHAR(32) NOT NULL", "fixedCode CHAR(8)", "payload VARBINARY(3000)",
            "amount DECIMAL(12,3)");
        AssertCreateSql(Provider.Oracle,
            "id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL",
            "code NVARCHAR2(32) NOT NULL", "fixedCode CHAR(8)", "payload BLOB", "amount NUMBER(12,3)");
        AssertCreateSql(Provider.PostgreSql,
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL",
            "code VARCHAR(32) NOT NULL", "fixedCode CHAR(8)", "payload BYTEA", "amount NUMERIC(12,3)");
    }

    [TestMethod]
    public void Pagination_UsesProviderSpecificSyntax()
    {
        var page = new PageParam { PageNumber = 3, PageSize = 10 };
        var orderBy = new OrderByCondition("id");

        Assert.AreEqual("SELECT * FROM sample ORDER BY id ASC LIMIT 20,10", CreateBuilder(Provider.Sqlite).Select(page, orderBy));
        Assert.AreEqual("SELECT * FROM sample ORDER BY id ASC LIMIT 20,10", CreateBuilder(Provider.MySql).Select(page, orderBy));
        Assert.AreEqual("SELECT * FROM sample ORDER BY id ASC LIMIT 20,10", CreateBuilder(Provider.MariaDb).Select(page, orderBy));
        Assert.AreEqual("SELECT * FROM sample ORDER BY id ASC OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
            CreateBuilder(Provider.SqlServer).Select(page, orderBy));
        Assert.AreEqual("SELECT * FROM sample ORDER BY id ASC OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
            CreateBuilder(Provider.Oracle).Select(page, orderBy));
        Assert.AreEqual("SELECT * FROM sample ORDER BY id ASC LIMIT 10 OFFSET 20",
            CreateBuilder(Provider.PostgreSql).Select(page, orderBy));
    }

    [TestMethod]
    public void SqlServerPagination_SuppliesRequiredFallbackOrdering()
    {
        var builder = new SqlServerBuilder();
        var page = new PageParam { PageNumber = 1, PageSize = 10 };

        Assert.AreEqual(
            "SELECT * FROM sample ORDER BY (SELECT NULL) ASC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY",
            builder.Select("sample", pageParam: page));
        Assert.AreEqual(
            "SELECT * FROM sample ORDER BY (SELECT NULL) ASC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY",
            builder.Select("sample", new WhereConditions(), pageParam: page));

        var where = new WhereConditions("tenantId", 1);
        Assert.AreEqual(
            "SELECT * FROM sample WHERE tenantId = @tenantId0 ORDER BY tenantId ASC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY",
            builder.Select("sample", where, pageParam: page));
    }

    [TestMethod]
    public void DropTable_UsesProviderCompatibleSyntax()
    {
        foreach (var provider in Enum.GetValues<Provider>())
        {
            var expected = provider == Provider.Oracle
                ? "DROP TABLE sample"
                : "DROP TABLE IF EXISTS sample";
            Assert.AreEqual(expected, CreateBuilder(provider).DropTable("sample"), provider.ToString());
        }
    }

    [TestMethod]
    public void DateTimeCast_UsesProviderCompatibleSyntax()
    {
        foreach (var provider in Enum.GetValues<Provider>())
        {
            var expected = provider switch
            {
                Provider.MySql or Provider.MariaDb or Provider.SqlServer => "CAST(createdAt AS DATETIME)",
                Provider.Oracle or Provider.PostgreSql => "CAST(createdAt AS TIMESTAMP)",
                _ => "CAST(createdAt AS DateTime)"
            };
            Assert.AreEqual(expected, CreateBuilder(provider).Cast("createdAt", DbType.DateTime), provider.ToString());
            Assert.ThrowsExactly<NotSupportedException>(() => CreateBuilder(provider).Cast("createdAt", DbType.Guid));
        }
    }

    [TestMethod]
    public void ParameterMarkers_UseProviderCompatiblePrefixes()
    {
        foreach (var provider in Enum.GetValues<Provider>())
        {
            var expected = provider == Provider.Oracle ? ":value" : "@value";
            Assert.AreEqual(expected, CreateBuilder(provider).ParameterName(new ValueParam(1, "value")));
        }
    }

    [TestMethod]
    public void OracleBatchInsert_UsesPre23CompatibleInsertAllSyntax()
    {
        var rows = new[]
        {
            new InputValues().Add("id", 1).Add("name", "one"),
            new InputValues().Add("name", "two").Add("id", 2)
        };

        var sql = new OracleBuilder().Insert("sample", rows, out var parameters);

        Assert.AreEqual(
            "INSERT ALL INTO sample (id,name) VALUES (:V0_id,:V0_name) "
            + "INTO sample (id,name) VALUES (:V1_id,:V1_name) SELECT 1 FROM DUAL",
            sql);
        CollectionAssert.AreEqual(
            new object[] { 1, "one", 2, "two" },
            parameters.Select(parameter => parameter.Value).ToArray());
    }

    private static readonly DbType[] SupportedDbTypes =
    [
        DbType.AnsiString, DbType.String, DbType.StringFixedLength, DbType.AnsiStringFixedLength,
        DbType.Xml, DbType.Guid, DbType.Binary, DbType.Object, DbType.Boolean, DbType.Byte,
        DbType.SByte, DbType.Int16, DbType.UInt16, DbType.Int32, DbType.UInt32, DbType.Int64,
        DbType.UInt64, DbType.Currency, DbType.Decimal, DbType.VarNumeric, DbType.Double,
        DbType.Single, DbType.Date, DbType.DateTime, DbType.DateTime2, DbType.DateTimeOffset, DbType.Time
    ];

    private static void AssertCreateSql(Provider provider, params string[] expectedFragments)
    {
        var sql = CreateBuilder(provider).CreateTable(new TableDefine(typeof(AllColumnShapesTable)));
        foreach (var expected in expectedFragments)
        {
            StringAssert.Contains(sql, expected, $"{provider}: {sql}");
        }
    }

    private static string ExpectedColumnType(Provider provider, DbType type)
    {
        return provider switch
        {
            Provider.Sqlite => type switch
            {
                DbType.AnsiString or DbType.String or DbType.StringFixedLength or DbType.AnsiStringFixedLength
                    or DbType.Xml or DbType.Guid => "TEXT",
                DbType.Binary or DbType.Object => "BLOB",
                DbType.Boolean or DbType.Byte or DbType.SByte or DbType.Int16 or DbType.UInt16
                    or DbType.Int32 or DbType.UInt32 or DbType.Int64 or DbType.UInt64 => "INTEGER",
                DbType.Currency or DbType.Decimal or DbType.VarNumeric or DbType.Double or DbType.Single => "REAL",
                _ => "TEXT"
            },
            Provider.MySql or Provider.MariaDb => type switch
            {
                DbType.AnsiString => "VARCHAR(255) CHARACTER SET latin1",
                DbType.String => "NVARCHAR(255)",
                DbType.StringFixedLength => "CHAR(255) CHARACTER SET utf8mb4",
                DbType.AnsiStringFixedLength => "CHAR(255) CHARACTER SET latin1",
                DbType.Binary or DbType.Object => "BLOB",
                DbType.Boolean => "TINYINT(1)",
                DbType.Byte or DbType.SByte or DbType.Int16 or DbType.UInt16 or DbType.Int32 or DbType.UInt32
                    or DbType.Int64 => "BIGINT",
                DbType.UInt64 => "BIGINT UNSIGNED",
                DbType.Currency or DbType.Decimal or DbType.VarNumeric => "DECIMAL(19,4)",
                DbType.Double => "DOUBLE",
                DbType.Single => "FLOAT",
                DbType.Date => "DATE",
                DbType.DateTime => "DATETIME",
                DbType.DateTime2 or DbType.DateTimeOffset => "DATETIME(6)",
                DbType.Time => "TIME",
                DbType.Guid => "CHAR(36)",
                DbType.Xml => "LONGTEXT",
                _ => throw new AssertFailedException(type.ToString())
            },
            Provider.SqlServer => type switch
            {
                DbType.AnsiString or DbType.AnsiStringFixedLength => "VARCHAR(255)",
                DbType.String or DbType.StringFixedLength => "NVARCHAR(255)",
                DbType.Binary or DbType.Object => "VARBINARY(MAX)",
                DbType.Boolean => "BIT",
                DbType.Byte or DbType.SByte or DbType.Int16 or DbType.UInt16 or DbType.Int32 or DbType.UInt32
                    or DbType.Int64 => "BIGINT",
                DbType.UInt64 => "DECIMAL(20,0)",
                DbType.Currency => "MONEY",
                DbType.Decimal or DbType.VarNumeric => "DECIMAL(38,18)",
                DbType.Double => "FLOAT",
                DbType.Single => "REAL",
                DbType.Date => "DATE",
                DbType.DateTime => "DATETIME",
                DbType.DateTime2 => "DATETIME2",
                DbType.DateTimeOffset => "DATETIMEOFFSET",
                DbType.Time => "TIME",
                DbType.Guid => "UNIQUEIDENTIFIER",
                DbType.Xml => "XML",
                _ => throw new AssertFailedException(type.ToString())
            },
            Provider.Oracle => type switch
            {
                DbType.AnsiString or DbType.String or DbType.StringFixedLength or DbType.AnsiStringFixedLength => "VARCHAR2(4000)",
                DbType.Xml => "XMLTYPE",
                DbType.Guid => "RAW(16)",
                DbType.Binary or DbType.Object => "BLOB",
                DbType.Boolean => "NUMBER(1)",
                DbType.Byte or DbType.SByte => "NUMBER(3)",
                DbType.Int16 or DbType.UInt16 => "NUMBER(5)",
                DbType.Int32 or DbType.UInt32 => "NUMBER(10)",
                DbType.Int64 => "NUMBER(19)",
                DbType.UInt64 => "NUMBER(20)",
                DbType.Currency => "NUMBER(19,4)",
                DbType.Decimal or DbType.VarNumeric => "NUMBER(38,18)",
                DbType.Double => "BINARY_DOUBLE",
                DbType.Single => "BINARY_FLOAT",
                DbType.Date or DbType.DateTime => "DATE",
                DbType.DateTime2 => "TIMESTAMP",
                DbType.DateTimeOffset => "TIMESTAMP WITH TIME ZONE",
                DbType.Time => "INTERVAL DAY TO SECOND",
                _ => throw new AssertFailedException(type.ToString())
            },
            Provider.PostgreSql => type switch
            {
                DbType.AnsiString or DbType.String or DbType.StringFixedLength or DbType.AnsiStringFixedLength => "TEXT",
                DbType.Xml => "XML",
                DbType.Guid => "UUID",
                DbType.Binary or DbType.Object => "BYTEA",
                DbType.Boolean => "BOOLEAN",
                DbType.Byte or DbType.SByte or DbType.Int16 => "SMALLINT",
                DbType.UInt16 or DbType.Int32 => "INTEGER",
                DbType.UInt32 or DbType.Int64 => "BIGINT",
                DbType.UInt64 => "NUMERIC(20)",
                DbType.Currency => "NUMERIC(19,4)",
                DbType.Decimal or DbType.VarNumeric => "NUMERIC",
                DbType.Double => "DOUBLE PRECISION",
                DbType.Single => "REAL",
                DbType.Date => "DATE",
                DbType.DateTime or DbType.DateTime2 => "TIMESTAMP WITHOUT TIME ZONE",
                DbType.DateTimeOffset => "TIMESTAMP WITH TIME ZONE",
                DbType.Time => "TIME WITHOUT TIME ZONE",
                _ => throw new AssertFailedException(type.ToString())
            },
            _ => throw new AssertFailedException(provider.ToString())
        };
    }

    private static IExposedBuilder CreateBuilder(Provider provider) => provider switch
    {
        Provider.Sqlite => new ExposedSqlBuilder(),
        Provider.MySql => new ExposedMySqlBuilder(),
        Provider.MariaDb => new ExposedMariaDbBuilder(),
        Provider.SqlServer => new ExposedSqlServerBuilder(),
        Provider.Oracle => new ExposedOracleBuilder(),
        Provider.PostgreSql => new ExposedPostgreSqlBuilder(),
        _ => throw new AssertFailedException(provider.ToString())
    };

    private interface IExposedBuilder
    {
        string ColumnType(DbType type);
        string CreateTable(TableDefine table);
        string Select(PageParam page, OrderByCondition orderBy);
        string DropTable(string tableName);
        string Cast(string column, DbType type);
        string ParameterName(ValueParam parameter);
    }

    private sealed class ExposedSqlBuilder : SqlBuilder, IExposedBuilder
    {
        public string ColumnType(DbType type) => base.GetColumnType(type);
        public string CreateTable(TableDefine table) => base.GetCreateTableSql(table);
        public string Select(PageParam page, OrderByCondition orderBy) => base.Select("sample", orderBy: orderBy, pageParam: page);
        public string DropTable(string tableName) => base.DropTableSql(tableName);
        public string Cast(string column, DbType type) => base.GetCastColumn(column, type);
        public string ParameterName(ValueParam parameter) => base.GetParamName(parameter);
    }

    private sealed class ExposedMySqlBuilder : MySqlBuilder, IExposedBuilder
    {
        public string ColumnType(DbType type) => base.GetColumnType(type);
        public string CreateTable(TableDefine table) => base.GetCreateTableSql(table);
        public string Select(PageParam page, OrderByCondition orderBy) => base.Select("sample", orderBy: orderBy, pageParam: page);
        public string DropTable(string tableName) => base.DropTableSql(tableName);
        public string Cast(string column, DbType type) => base.GetCastColumn(column, type);
        public string ParameterName(ValueParam parameter) => base.GetParamName(parameter);
    }

    private sealed class ExposedMariaDbBuilder : MariaDbBuilder, IExposedBuilder
    {
        public string ColumnType(DbType type) => base.GetColumnType(type);
        public string CreateTable(TableDefine table) => base.GetCreateTableSql(table);
        public string Select(PageParam page, OrderByCondition orderBy) => base.Select("sample", orderBy: orderBy, pageParam: page);
        public string DropTable(string tableName) => base.DropTableSql(tableName);
        public string Cast(string column, DbType type) => base.GetCastColumn(column, type);
        public string ParameterName(ValueParam parameter) => base.GetParamName(parameter);
    }

    private sealed class ExposedSqlServerBuilder : SqlServerBuilder, IExposedBuilder
    {
        public string ColumnType(DbType type) => base.GetColumnType(type);
        public string CreateTable(TableDefine table) => base.GetCreateTableSql(table);
        public string Select(PageParam page, OrderByCondition orderBy) => base.Select("sample", orderBy: orderBy, pageParam: page);
        public string DropTable(string tableName) => base.DropTableSql(tableName);
        public string Cast(string column, DbType type) => base.GetCastColumn(column, type);
        public string ParameterName(ValueParam parameter) => base.GetParamName(parameter);
    }

    private sealed class ExposedOracleBuilder : OracleBuilder, IExposedBuilder
    {
        public string ColumnType(DbType type) => base.GetColumnType(type);
        public string CreateTable(TableDefine table) => base.GetCreateTableSql(table);
        public string Select(PageParam page, OrderByCondition orderBy) => base.Select("sample", orderBy: orderBy, pageParam: page);
        public string DropTable(string tableName) => base.DropTableSql(tableName);
        public string Cast(string column, DbType type) => base.GetCastColumn(column, type);
        public string ParameterName(ValueParam parameter) => base.GetParamName(parameter);
    }

    private sealed class ExposedPostgreSqlBuilder : PostgreSqlBuilder, IExposedBuilder
    {
        public string ColumnType(DbType type) => base.GetColumnType(type);
        public string CreateTable(TableDefine table) => base.GetCreateTableSql(table);
        public string Select(PageParam page, OrderByCondition orderBy) => base.Select("sample", orderBy: orderBy, pageParam: page);
        public string DropTable(string tableName) => base.DropTableSql(tableName);
        public string Cast(string column, DbType type) => base.GetCastColumn(column, type);
        public string ParameterName(ValueParam parameter) => base.GetParamName(parameter);
    }

    private enum Provider { Sqlite, MySql, MariaDb, SqlServer, Oracle, PostgreSql }

    private static class AllColumnShapesTable
    {
        [DbTableName] internal const string TableName = "AllColumnShapes";
        [DbPrimaryKeyIdentity] internal const string Id = "id";
        [DbColumnString(Length = 32, AllowUnicode = true)] internal const string Code = "code";
        [DbColumnString(Length = 8, FixedLength = true, AllowEmpty = true)] internal const string FixedCode = "fixedCode";
        [DbColumnBinary(Length = 3000, AllowEmpty = true)] internal const string Payload = "payload";
        [DbColumnDecimal(Length = 12, PointLength = 3, AllowEmpty = true)] internal const string Amount = "amount";
    }
}
