using CoddLoom.Params;
using CoddLoom.PostgreSql;
using CoddLoom.Table;
using CoddLoom.Table.Base;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Data;

namespace CoddLoom.Tests.DbTest;

[TestClass]
public class PostgreSqlBuilderTest
{
    [TestMethod]
    public void Select_WithPagination_UsesPostgreSqlLimitSyntax()
    {
        var builder = new PostgreSqlBuilder();

        var sql = builder.Select("events", pageParam: new PageParam
        {
            PageNumber = 3,
            PageSize = 20
        });

        Assert.AreEqual("SELECT * FROM events LIMIT 20 OFFSET 40", sql);
    }

    [TestMethod]
    public void CreateTable_WithIdentityPrimaryKey_UsesGeneratedIdentity()
    {
        var builder = new ExposedPostgreSqlBuilder();
        var table = new TableDefine(typeof(IdentityTable));

        var sql = builder.CreateTable(table);

        StringAssert.Contains(sql, "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL");
        Assert.DoesNotContain("AUTOINCREMENT", sql);
    }

    [TestMethod]
    public void ColumnTypes_UsePostgreSqlNativeTypes()
    {
        var builder = new ExposedPostgreSqlBuilder();

        Assert.AreEqual("BOOLEAN", builder.ColumnType(DbType.Boolean));
        Assert.AreEqual("BYTEA", builder.ColumnType(DbType.Binary));
        Assert.AreEqual("UUID", builder.ColumnType(DbType.Guid));
        Assert.AreEqual("TIMESTAMP WITH TIME ZONE", builder.ColumnType(DbType.DateTimeOffset));
        Assert.AreEqual("DOUBLE PRECISION", builder.ColumnType(DbType.Double));
    }

    private sealed class ExposedPostgreSqlBuilder : PostgreSqlBuilder
    {
        public string CreateTable(TableDefine table) => base.GetCreateTableSql(table);

        public string ColumnType(DbType type) => base.GetColumnType(type);
    }

    private static class IdentityTable
    {
        [DbTableName]
        internal const string TableName = "IdentityTable";

        [DbPrimaryKeyIdentity]
        internal const string Id = "id";

        [DbColumnString]
        internal const string Name = "name";
    }
}
