<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Description>MySQL provider for CoddLoom.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoddLoom\CoddLoom.csproj" />
  </ItemGroup>

</Project>
