<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	  <LangVersion>latest</LangVersion>
	  <Description>SQL Server provider for CoddLoom.</Description>
  </PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
	  <PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" Version="7.0.2" />
	</ItemGroup>

	<ItemGroup>
	  <InternalsVisibleTo Include="CoddLoom.Tests" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CoddLoom\CoddLoom.csproj" />
	</ItemGroup>

</Project>
