<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Description>SQLite provider for CoddLoom.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite" Version="2.0.4" />
    <PackageReference Include="SourceGear.sqlite3" Version="3.53.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoddLoom\CoddLoom.csproj" />
  </ItemGroup>

</Project>
