<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.4.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.4.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CoddLoom.MySql\CoddLoom.MySql.csproj" />
    <ProjectReference Include="..\..\src\CoddLoom.Sqlite\CoddLoom.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\CoddLoom.SqlServer\CoddLoom.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\CoddLoom.MariaDb\CoddLoom.MariaDb.csproj" />
    <ProjectReference Include="..\..\src\CoddLoom.Oracle\CoddLoom.Oracle.csproj" />
    <ProjectReference Include="..\..\src\CoddLoom.PostgreSql\CoddLoom.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\CoddLoom\CoddLoom.csproj" />
  </ItemGroup>

</Project>
