<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Description>PostgreSQL provider for CoddLoom.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoddLoom\CoddLoom.csproj" />
  </ItemGroup>

</Project>
