using CoddLoom.Params;
using CoddLoom.Sql;
using CoddLoom.Table;
using CoddLoom.Table.Base;
using System;
using System.Collections.Generic;
using System.Data;

namespace CoddLoom.PostgreSql;

public class PostgreSqlBuilder : SqlBuilder
{
    protected override string AppendLimit(string sql, PageParam pageParam = null)
    {
        if (pageParam == null) return sql;
        return $"{sql} LIMIT {pageParam.PageSize} OFFSET {pageParam.Offset}";
    }

    protected override string GetPrimaryKeySql(DbPrimaryKeyBaseAttribute primaryKey)
    {
        return $"{primaryKey.Name} {GetColumnTypeSql(primaryKey)} PRIMARY KEY NOT NULL";
    }

    protected override string GetColumnType(DbType type)
    {
        switch (type)
        {
            case DbType.AnsiString:
            case DbType.String:
            case DbType.StringFixedLength:
            case DbType.AnsiStringFixedLength:
                return "TEXT";
            case DbType.Xml:
                return "XML";
            case DbType.Guid:
                return "UUID";
            case DbType.Binary:
            case DbType.Object:
                return "BYTEA";
            case DbType.Boolean:
                return "BOOLEAN";
            case DbType.Byte:
            case DbType.SByte:
            case DbType.Int16:
                return "SMALLINT";
            case DbType.UInt16:
            case DbType.Int32:
                return "INTEGER";
            case DbType.UInt32:
            case DbType.Int64:
                return "BIGINT";
            case DbType.UInt64:
                return "NUMERIC(20)";
            case DbType.Currency:
                return "NUMERIC(19,4)";
            case DbType.Decimal:
            case DbType.VarNumeric:
                return "NUMERIC";
            case DbType.Double:
                return "DOUBLE PRECISION";
            case DbType.Single:
                return "REAL";
            case DbType.Date:
                return "DATE";
            case DbType.DateTime:
            case DbType.DateTime2:
                return "TIMESTAMP WITHOUT TIME ZONE";
            case DbType.DateTimeOffset:
                return "TIMESTAMP WITH TIME ZONE";
            case DbType.Time:
                return "TIME WITHOUT TIME ZONE";
            default:
                throw new NotSupportedException($"{type} not support for column.");
        }
    }

    protected override string GetStringColumnType(IStringColumn column)
    {
        var type = column.FixedLength ? "CHAR" : "VARCHAR";
        return $"{type}({column.Length})";
    }

    protected override string GetBinaryColumnType(DbColumnBinaryAttribute binaryColumn)
    {
        return "BYTEA";
    }

    protected override string GetIdentityColumnType(DbPrimaryKeyIdentityAttribute column)
    {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY";
    }

    protected override string GetDecimalColumnType(DbColumnDecimalAttribute decimalColumn)
    {
        return $"NUMERIC({decimalColumn.Length},{decimalColumn.PointLength})";
    }

    protected override string GetCastColumn(string column, DbType dbType)
    {
        if (dbType == DbType.DateTime)
        {
            return $"CAST({column} AS TIMESTAMP)";
        }

        return base.GetCastColumn(column, dbType);
    }

    protected override string GetTableExistsSql(TableDefine table, out List<ValueParam> dbParams)
    {
        var tableNameParam = new ValueParam(table.Name.ToLowerInvariant(), "schema_table_name");
        dbParams = new List<ValueParam> { tableNameParam };
        return "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES "
            + "WHERE TABLE_SCHEMA = current_schema() AND TABLE_TYPE = 'BASE TABLE' "
            + $"AND TABLE_NAME = {GetParamName(tableNameParam)}";
    }

    protected override string GetTableColumnsSql(TableDefine table, out List<ValueParam> dbParams)
    {
        var tableNameParam = new ValueParam(table.Name.ToLowerInvariant(), "schema_table_name");
        dbParams = new List<ValueParam> { tableNameParam };
        return "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS "
            + "WHERE TABLE_SCHEMA = current_schema() "
            + $"AND TABLE_NAME = {GetParamName(tableNameParam)} ORDER BY ORDINAL_POSITION";
    }
}
