<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Description>MariaDB provider for CoddLoom.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoddLoom\CoddLoom.csproj" />
  </ItemGroup>

</Project>
