<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Description>Oracle Database provider for CoddLoom.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoddLoom\CoddLoom.csproj" />
  </ItemGroup>

</Project>
