using CoddLoom.Sql;
using CoddLoom.Params;
using CoddLoom.Table;
using System;
using System.Collections.Generic;
using System.Data;
using CoddLoom.Table.Base;

namespace CoddLoom.Oracle;

public class OracleBuilder : SqlBuilder
{
    protected override string AppendLimit(string sql, PageParam pageParam = null)
    {
        if (pageParam == null) return sql;
        return $"{sql} OFFSET {pageParam.Offset} ROWS FETCH NEXT {pageParam.PageSize} ROWS ONLY";
    }

    protected override string GetPrimaryKeySql(DbPrimaryKeyBaseAttribute primaryKey)
    {
        return $"{primaryKey.Name} {GetColumnTypeSql(primaryKey)} PRIMARY KEY NOT NULL";
    }

    protected override string GetColumnType(DbType type)
    {
        switch (type)
        {
            case DbType.AnsiString:
            case DbType.String:
            case DbType.AnsiStringFixedLength:
            case DbType.StringFixedLength:
                return "VARCHAR2(4000)";
            case DbType.Xml:
                return "XMLTYPE";
            case DbType.Guid:
                return "RAW(16)";
            case DbType.Binary:
            case DbType.Object:
                return "BLOB";
            case DbType.Boolean:
                return "NUMBER(1)";
            case DbType.Byte:
            case DbType.SByte:
                return "NUMBER(3)";
            case DbType.Int16:
            case DbType.UInt16:
                return "NUMBER(5)";
            case DbType.Int32:
            case DbType.UInt32:
                return "NUMBER(10)";
            case DbType.Int64:
                return "NUMBER(19)";
            case DbType.UInt64:
                return "NUMBER(20)";
            case DbType.Currency:
                return "NUMBER(19,4)";
            case DbType.Decimal:
            case DbType.VarNumeric:
                return "NUMBER(38,18)";
            case DbType.Double:
                return "BINARY_DOUBLE";
            case DbType.Single:
                return "BINARY_FLOAT";
            case DbType.Date:
            case DbType.DateTime:
                return "DATE";
            case DbType.DateTime2:
                return "TIMESTAMP";
            case DbType.DateTimeOffset:
                return "TIMESTAMP WITH TIME ZONE";
            case DbType.Time:
                return "INTERVAL DAY TO SECOND";
            default:
                throw new NotSupportedException($"{type} not support for column.");
        }
    }

    protected override string GetStringColumnType(IStringColumn column)
    {
        var type = column.AllowUnicode
            ? (column.FixedLength ? "NCHAR" : "NVARCHAR2")
            : (column.FixedLength ? "CHAR" : "VARCHAR2");
        return $"{type}({column.Length})";
    }

    protected override string GetBinaryColumnType(DbColumnBinaryAttribute binaryColumn)
    {
        return binaryColumn.Length <= 2000 ? $"RAW({binaryColumn.Length})" : "BLOB";
    }

    protected override string GetIdentityColumnType(DbPrimaryKeyIdentityAttribute column)
        => "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY";

    protected override string GetDecimalColumnType(DbColumnDecimalAttribute decimalColumn)
        => $"NUMBER({decimalColumn.Length},{decimalColumn.PointLength})";

    protected override string GetCastColumn(string column, DbType dbType)
    {
        return dbType == DbType.DateTime
            ? $"CAST({column} AS TIMESTAMP)"
            : base.GetCastColumn(column, dbType);
    }

    protected override string GetParamName(ValueParam param) => $":{param.ParamName}";

    protected override string DropTableSql(string tableName) => $"DROP TABLE {tableName}";

    protected override string GetTableExistsSql(TableDefine table, out List<ValueParam> dbParams)
    {
        var tableNameParam = new ValueParam(table.Name.ToUpperInvariant(), "schema_table_name");
        dbParams = new List<ValueParam> { tableNameParam };
        return $"SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = {GetParamName(tableNameParam)}";
    }

    protected override string GetTableColumnsSql(TableDefine table, out List<ValueParam> dbParams)
    {
        var tableNameParam = new ValueParam(table.Name.ToUpperInvariant(), "schema_table_name");
        dbParams = new List<ValueParam> { tableNameParam };
        return "SELECT COLUMN_NAME FROM USER_TAB_COLUMNS "
            + $"WHERE TABLE_NAME = {GetParamName(tableNameParam)} ORDER BY COLUMN_ID";
    }
}
